name: Build and Deploy (Astro → SFTP)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with: { version: 9 }
        
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          
      - name: Install deps
        run: pnpm install --frozen-lockfile
        
      - name: Build Astro
        run: pnpm build

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}          # default 22
          local_path: dist/*
          remote_path: ${{ secrets.SFTP_DEST }}   # e.g. /var/www/html/
          sftp_only: true
