name: Build and Deploy (Astro → SFTP)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with: { version: 9 }
        
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          
      - name: Install deps
        run: pnpm install --frozen-lockfile
        
      - name: Build Astro
        run: pnpm build

      - name: Deploy to Server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_SERVER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: './dist/*'
          remote_path: ${{ secrets.SFTP_DEST }}
          sftpArgs: '-o ConnectTimeout=5'
